version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_case_management
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}

  mysql:
    image: mysql:8.1
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Thisisok
      MYSQL_DATABASE: testing
      MYSQL_USER: testing
      MYSQL_PASSWORD: Thisisok
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
